import Head from "next/head";
import AppFooter from "./app-footer";
import AppTitle from "./app-title";
import styles from "./AppLayout.module.css";

export default function AppLayout({ children }: any) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>pawelpiotrowski.dev</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div className={styles.header}>
            <AppTitle />
          </div>
          {children}
          <div className={styles.footer}>
            <AppFooter />
          </div>
        </main>
      </div>
    </>
  );
}
